import type {EquipmentDefinition} from "@/lib/game/items";

export function formatPercentBasisPoints(value:number){return `${value/100}%`}
export function formatEquipmentEffect(kind:EquipmentDefinition["effectKind"],value:number){switch(kind){case"regeneration":return `Restores ${value} HP every effective hour`;case"damage":return `+${formatPercentBasisPoints(value)} outgoing damage`;case"dodge":return `+${formatPercentBasisPoints(value)} dodge chance`;case"potion":return `+${formatPercentBasisPoints(value)} potion healing`;case"protection":return `-${formatPercentBasisPoints(value)} incoming player damage`;case"hospital":return `-${value} minutes Hospital time`;case"gold":return `Generates ${value} coins every 2 effective hours`;case"chest":return `+${formatPercentBasisPoints(value)} extra Chest reward chance`;case"thorns":return `${formatPercentBasisPoints(value)} reflected/reduced damage`;case"phoenix":return `${formatPercentBasisPoints(value)} Phoenix chance`}}
export function formatFullSetBonus(definition:EquipmentDefinition){return definition.fullSetBonus===0?"No additional full-set bonus":formatEquipmentEffect(definition.effectKind,definition.fullSetBonus)}
export function serverAnchoredRemainingMs(serverNow:string,cooldownEndsAt:string|null,monotonicElapsedMs:number){if(!cooldownEndsAt)return 0;return Math.max(0,Date.parse(cooldownEndsAt)-(Date.parse(serverNow)+Math.max(0,monotonicElapsedMs)))}
export function formatCooldown(ms:number){const seconds=Math.ceil(Math.max(0,ms)/1000),minutes=Math.floor(seconds/60);return `${String(minutes).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`}
export type ConsumableEligibility={currentHp:number;maxHp:number;currentLevel:number;isMaxLevel:boolean;gameplayStatus:string;eligibleHourglassCooldowns:number};
export function consumableDisabledReason(id:string,eligibility:ConsumableEligibility){if(id==="discharge_pill")return"Use this from the Hospital screen.";if(eligibility.gameplayStatus!=="active")return"Your current player status prevents Inventory use.";if((id==="small_health_potion"||id==="big_health_potion")&&eligibility.currentHp>=eligibility.maxHp)return"You are already at full HP.";if((id==="xp_candy"||id==="experience_potion")&&eligibility.isMaxLevel)return"XP items cannot be used at Level 40.";if(id==="golden_hourglass"&&eligibility.eligibleHourglassCooldowns<1)return"No eligible Action cooldown is active.";return null}
export type HospitalViewState={active:boolean;hospitalUntil:string|null;pillQuantity:number;pillAlreadyUsed:boolean};
export function hospitalDisabledReason(view:HospitalViewState){if(!view.active)return"You are not currently hospitalized.";if(view.pillAlreadyUsed)return"A Discharge Pill was already used during this Hospital stay.";if(view.pillQuantity<1)return"You do not own a Discharge Pill.";return null}
