begin;

insert into public.festivals (id, name, time_zone, starts_at, ends_at, config)
values (
  'kempape-2026',
  'Kempape 2026',
  'Europe/Berlin',
  '2026-07-16T11:30:00+02:00',
  '2026-07-20T03:00:00+02:00',
  '{"cycleCount":4,"finalMidnightCreatesNewCycle":false}'::jsonb
)
on conflict (id) do update set
  name = excluded.name,
  time_zone = excluded.time_zone,
  starts_at = excluded.starts_at,
  ends_at = excluded.ends_at,
  config = excluded.config;

insert into public.action_definitions (id,name,tier,hp_cost,xp_percentage,coin_reward,cooldown_minutes,daily_cap,festival_cap,requires_unique_person,requires_unique_group,requires_unique_item,is_extreme_challenge,is_enabled) values ('smoke_cigarette','Smoke a Cigarette','common',6,0.15,10,10,null,null,false,false,false,false,true) on conflict (id) do update set name=excluded.name, tier=excluded.tier, hp_cost=excluded.hp_cost, xp_percentage=excluded.xp_percentage, coin_reward=excluded.coin_reward, cooldown_minutes=excluded.cooldown_minutes, daily_cap=excluded.daily_cap, festival_cap=excluded.festival_cap, requires_unique_person=excluded.requires_unique_person, requires_unique_group=excluded.requires_unique_group, requires_unique_item=excluded.requires_unique_item, is_extreme_challenge=excluded.is_extreme_challenge, is_enabled=excluded.is_enabled;
insert into public.action_definitions (id,name,tier,hp_cost,xp_percentage,coin_reward,cooldown_minutes,daily_cap,festival_cap,requires_unique_person,requires_unique_group,requires_unique_item,is_extreme_challenge,is_enabled) values ('drink_beer','Drink a Beer','common',10,0.15,10,10,null,null,false,false,false,false,true) on conflict (id) do update set name=excluded.name, tier=excluded.tier, hp_cost=excluded.hp_cost, xp_percentage=excluded.xp_percentage, coin_reward=excluded.coin_reward, cooldown_minutes=excluded.cooldown_minutes, daily_cap=excluded.daily_cap, festival_cap=excluded.festival_cap, requires_unique_person=excluded.requires_unique_person, requires_unique_group=excluded.requires_unique_group, requires_unique_item=excluded.requires_unique_item, is_extreme_challenge=excluded.is_extreme_challenge, is_enabled=excluded.is_enabled;
insert into public.action_definitions (id,name,tier,hp_cost,xp_percentage,coin_reward,cooldown_minutes,daily_cap,festival_cap,requires_unique_person,requires_unique_group,requires_unique_item,is_extreme_challenge,is_enabled) values ('strong_mixed_drink','Drink a Strong Mixed Drink','rare',14,0.35,25,10,null,null,false,false,false,false,true) on conflict (id) do update set name=excluded.name, tier=excluded.tier, hp_cost=excluded.hp_cost, xp_percentage=excluded.xp_percentage, coin_reward=excluded.coin_reward, cooldown_minutes=excluded.cooldown_minutes, daily_cap=excluded.daily_cap, festival_cap=excluded.festival_cap, requires_unique_person=excluded.requires_unique_person, requires_unique_group=excluded.requires_unique_group, requires_unique_item=excluded.requires_unique_item, is_extreme_challenge=excluded.is_extreme_challenge, is_enabled=excluded.is_enabled;
insert into public.action_definitions (id,name,tier,hp_cost,xp_percentage,coin_reward,cooldown_minutes,daily_cap,festival_cap,requires_unique_person,requires_unique_group,requires_unique_item,is_extreme_challenge,is_enabled) values ('take_shot','Take a Shot','rare',18,0.35,25,10,null,null,false,false,false,false,true) on conflict (id) do update set name=excluded.name, tier=excluded.tier, hp_cost=excluded.hp_cost, xp_percentage=excluded.xp_percentage, coin_reward=excluded.coin_reward, cooldown_minutes=excluded.cooldown_minutes, daily_cap=excluded.daily_cap, festival_cap=excluded.festival_cap, requires_unique_person=excluded.requires_unique_person, requires_unique_group=excluded.requires_unique_group, requires_unique_item=excluded.requires_unique_item, is_extreme_challenge=excluded.is_extreme_challenge, is_enabled=excluded.is_enabled;
insert into public.action_definitions (id,name,tier,hp_cost,xp_percentage,coin_reward,cooldown_minutes,daily_cap,festival_cap,requires_unique_person,requires_unique_group,requires_unique_item,is_extreme_challenge,is_enabled) values ('jagermeister_shot','Take a Jägermeister Shot','epic',24,0.6,50,10,null,null,false,false,false,false,true) on conflict (id) do update set name=excluded.name, tier=excluded.tier, hp_cost=excluded.hp_cost, xp_percentage=excluded.xp_percentage, coin_reward=excluded.coin_reward, cooldown_minutes=excluded.cooldown_minutes, daily_cap=excluded.daily_cap, festival_cap=excluded.festival_cap, requires_unique_person=excluded.requires_unique_person, requires_unique_group=excluded.requires_unique_group, requires_unique_item=excluded.requires_unique_item, is_extreme_challenge=excluded.is_extreme_challenge, is_enabled=excluded.is_enabled;
insert into public.action_definitions (id,name,tier,hp_cost,xp_percentage,coin_reward,cooldown_minutes,daily_cap,festival_cap,requires_unique_person,requires_unique_group,requires_unique_item,is_extreme_challenge,is_enabled) values ('smoke_joint','Smoke a Joint','epic',30,0.6,50,10,null,null,false,false,false,false,true) on conflict (id) do update set name=excluded.name, tier=excluded.tier, hp_cost=excluded.hp_cost, xp_percentage=excluded.xp_percentage, coin_reward=excluded.coin_reward, cooldown_minutes=excluded.cooldown_minutes, daily_cap=excluded.daily_cap, festival_cap=excluded.festival_cap, requires_unique_person=excluded.requires_unique_person, requires_unique_group=excluded.requires_unique_group, requires_unique_item=excluded.requires_unique_item, is_extreme_challenge=excluded.is_extreme_challenge, is_enabled=excluded.is_enabled;
insert into public.action_definitions (id,name,tier,hp_cost,xp_percentage,coin_reward,cooldown_minutes,daily_cap,festival_cap,requires_unique_person,requires_unique_group,requires_unique_item,is_extreme_challenge,is_enabled) values ('finish_drink','Finish Your Drink','legendary',37,0.9,100,10,null,null,false,false,false,false,true) on conflict (id) do update set name=excluded.name, tier=excluded.tier, hp_cost=excluded.hp_cost, xp_percentage=excluded.xp_percentage, coin_reward=excluded.coin_reward, cooldown_minutes=excluded.cooldown_minutes, daily_cap=excluded.daily_cap, festival_cap=excluded.festival_cap, requires_unique_person=excluded.requires_unique_person, requires_unique_group=excluded.requires_unique_group, requires_unique_item=excluded.requires_unique_item, is_extreme_challenge=excluded.is_extreme_challenge, is_enabled=excluded.is_enabled;
insert into public.action_definitions (id,name,tier,hp_cost,xp_percentage,coin_reward,cooldown_minutes,daily_cap,festival_cap,requires_unique_person,requires_unique_group,requires_unique_item,is_extreme_challenge,is_enabled) values ('extreme_festival_challenge','Extreme Festival Challenge','legendary',60,1.5,150,null,1,null,false,false,false,true,false) on conflict (id) do update set name=excluded.name, tier=excluded.tier, hp_cost=excluded.hp_cost, xp_percentage=excluded.xp_percentage, coin_reward=excluded.coin_reward, cooldown_minutes=excluded.cooldown_minutes, daily_cap=excluded.daily_cap, festival_cap=excluded.festival_cap, requires_unique_person=excluded.requires_unique_person, requires_unique_group=excluded.requires_unique_group, requires_unique_item=excluded.requires_unique_item, is_extreme_challenge=excluded.is_extreme_challenge, is_enabled=excluded.is_enabled;
insert into public.action_definitions (id,name,tier,hp_cost,xp_percentage,coin_reward,cooldown_minutes,daily_cap,festival_cap,requires_unique_person,requires_unique_group,requires_unique_item,is_extreme_challenge,is_enabled) values ('pushups_20','20 Push-ups','common',0,0.15,10,60,5,null,false,false,false,false,true) on conflict (id) do update set name=excluded.name, tier=excluded.tier, hp_cost=excluded.hp_cost, xp_percentage=excluded.xp_percentage, coin_reward=excluded.coin_reward, cooldown_minutes=excluded.cooldown_minutes, daily_cap=excluded.daily_cap, festival_cap=excluded.festival_cap, requires_unique_person=excluded.requires_unique_person, requires_unique_group=excluded.requires_unique_group, requires_unique_item=excluded.requires_unique_item, is_extreme_challenge=excluded.is_extreme_challenge, is_enabled=excluded.is_enabled;
insert into public.action_definitions (id,name,tier,hp_cost,xp_percentage,coin_reward,cooldown_minutes,daily_cap,festival_cap,requires_unique_person,requires_unique_group,requires_unique_item,is_extreme_challenge,is_enabled) values ('squats_40','40 Squats','common',0,0.15,10,60,5,null,false,false,false,false,true) on conflict (id) do update set name=excluded.name, tier=excluded.tier, hp_cost=excluded.hp_cost, xp_percentage=excluded.xp_percentage, coin_reward=excluded.coin_reward, cooldown_minutes=excluded.cooldown_minutes, daily_cap=excluded.daily_cap, festival_cap=excluded.festival_cap, requires_unique_person=excluded.requires_unique_person, requires_unique_group=excluded.requires_unique_group, requires_unique_item=excluded.requires_unique_item, is_extreme_challenge=excluded.is_extreme_challenge, is_enabled=excluded.is_enabled;
insert into public.action_definitions (id,name,tier,hp_cost,xp_percentage,coin_reward,cooldown_minutes,daily_cap,festival_cap,requires_unique_person,requires_unique_group,requires_unique_item,is_extreme_challenge,is_enabled) values ('cold_shower','Cold Shower','common',0,0.15,10,240,2,null,false,false,false,false,true) on conflict (id) do update set name=excluded.name, tier=excluded.tier, hp_cost=excluded.hp_cost, xp_percentage=excluded.xp_percentage, coin_reward=excluded.coin_reward, cooldown_minutes=excluded.cooldown_minutes, daily_cap=excluded.daily_cap, festival_cap=excluded.festival_cap, requires_unique_person=excluded.requires_unique_person, requires_unique_group=excluded.requires_unique_group, requires_unique_item=excluded.requires_unique_item, is_extreme_challenge=excluded.is_extreme_challenge, is_enabled=excluded.is_enabled;
insert into public.action_definitions (id,name,tier,hp_cost,xp_percentage,coin_reward,cooldown_minutes,daily_cap,festival_cap,requires_unique_person,requires_unique_group,requires_unique_item,is_extreme_challenge,is_enabled) values ('paid_shower','Pay for a Shower','rare',0,0.35,25,null,1,null,false,false,false,false,true) on conflict (id) do update set name=excluded.name, tier=excluded.tier, hp_cost=excluded.hp_cost, xp_percentage=excluded.xp_percentage, coin_reward=excluded.coin_reward, cooldown_minutes=excluded.cooldown_minutes, daily_cap=excluded.daily_cap, festival_cap=excluded.festival_cap, requires_unique_person=excluded.requires_unique_person, requires_unique_group=excluded.requires_unique_group, requires_unique_item=excluded.requires_unique_item, is_extreme_challenge=excluded.is_extreme_challenge, is_enabled=excluded.is_enabled;
insert into public.action_definitions (id,name,tier,hp_cost,xp_percentage,coin_reward,cooldown_minutes,daily_cap,festival_cap,requires_unique_person,requires_unique_group,requires_unique_item,is_extreme_challenge,is_enabled) values ('find_known_person','Find Someone You Know','common',0,0.15,10,null,null,null,true,false,false,false,true) on conflict (id) do update set name=excluded.name, tier=excluded.tier, hp_cost=excluded.hp_cost, xp_percentage=excluded.xp_percentage, coin_reward=excluded.coin_reward, cooldown_minutes=excluded.cooldown_minutes, daily_cap=excluded.daily_cap, festival_cap=excluded.festival_cap, requires_unique_person=excluded.requires_unique_person, requires_unique_group=excluded.requires_unique_group, requires_unique_item=excluded.requires_unique_item, is_extreme_challenge=excluded.is_extreme_challenge, is_enabled=excluded.is_enabled;
insert into public.action_definitions (id,name,tier,hp_cost,xp_percentage,coin_reward,cooldown_minutes,daily_cap,festival_cap,requires_unique_person,requires_unique_group,requires_unique_item,is_extreme_challenge,is_enabled) values ('talk_stranger_20','Talk to a Stranger for 20+ Minutes','rare',0,0.35,25,null,2,null,true,false,false,false,true) on conflict (id) do update set name=excluded.name, tier=excluded.tier, hp_cost=excluded.hp_cost, xp_percentage=excluded.xp_percentage, coin_reward=excluded.coin_reward, cooldown_minutes=excluded.cooldown_minutes, daily_cap=excluded.daily_cap, festival_cap=excluded.festival_cap, requires_unique_person=excluded.requires_unique_person, requires_unique_group=excluded.requires_unique_group, requires_unique_item=excluded.requires_unique_item, is_extreme_challenge=excluded.is_extreme_challenge, is_enabled=excluded.is_enabled;
insert into public.action_definitions (id,name,tier,hp_cost,xp_percentage,coin_reward,cooldown_minutes,daily_cap,festival_cap,requires_unique_person,requires_unique_group,requires_unique_item,is_extreme_challenge,is_enabled) values ('find_catalans','Find Catalan People','rare',0,0.35,25,null,1,null,false,true,false,false,true) on conflict (id) do update set name=excluded.name, tier=excluded.tier, hp_cost=excluded.hp_cost, xp_percentage=excluded.xp_percentage, coin_reward=excluded.coin_reward, cooldown_minutes=excluded.cooldown_minutes, daily_cap=excluded.daily_cap, festival_cap=excluded.festival_cap, requires_unique_person=excluded.requires_unique_person, requires_unique_group=excluded.requires_unique_group, requires_unique_item=excluded.requires_unique_item, is_extreme_challenge=excluded.is_extreme_challenge, is_enabled=excluded.is_enabled;
insert into public.action_definitions (id,name,tier,hp_cost,xp_percentage,coin_reward,cooldown_minutes,daily_cap,festival_cap,requires_unique_person,requires_unique_group,requires_unique_item,is_extreme_challenge,is_enabled) values ('make_out','Make Out With Someone','epic',0,0.6,50,null,1,null,true,false,false,false,true) on conflict (id) do update set name=excluded.name, tier=excluded.tier, hp_cost=excluded.hp_cost, xp_percentage=excluded.xp_percentage, coin_reward=excluded.coin_reward, cooldown_minutes=excluded.cooldown_minutes, daily_cap=excluded.daily_cap, festival_cap=excluded.festival_cap, requires_unique_person=excluded.requires_unique_person, requires_unique_group=excluded.requires_unique_group, requires_unique_item=excluded.requires_unique_item, is_extreme_challenge=excluded.is_extreme_challenge, is_enabled=excluded.is_enabled;
insert into public.action_definitions (id,name,tier,hp_cost,xp_percentage,coin_reward,cooldown_minutes,daily_cap,festival_cap,requires_unique_person,requires_unique_group,requires_unique_item,is_extreme_challenge,is_enabled) values ('have_sex','Have Sex With Someone','legendary',0,0.9,100,null,null,1,true,false,false,false,true) on conflict (id) do update set name=excluded.name, tier=excluded.tier, hp_cost=excluded.hp_cost, xp_percentage=excluded.xp_percentage, coin_reward=excluded.coin_reward, cooldown_minutes=excluded.cooldown_minutes, daily_cap=excluded.daily_cap, festival_cap=excluded.festival_cap, requires_unique_person=excluded.requires_unique_person, requires_unique_group=excluded.requires_unique_group, requires_unique_item=excluded.requires_unique_item, is_extreme_challenge=excluded.is_extreme_challenge, is_enabled=excluded.is_enabled;
insert into public.action_definitions (id,name,tier,hp_cost,xp_percentage,coin_reward,cooldown_minutes,daily_cap,festival_cap,requires_unique_person,requires_unique_group,requires_unique_item,is_extreme_challenge,is_enabled) values ('tattoo','Get a Permanent Tattoo','legendary',0,0.9,100,null,null,1,false,false,false,false,true) on conflict (id) do update set name=excluded.name, tier=excluded.tier, hp_cost=excluded.hp_cost, xp_percentage=excluded.xp_percentage, coin_reward=excluded.coin_reward, cooldown_minutes=excluded.cooldown_minutes, daily_cap=excluded.daily_cap, festival_cap=excluded.festival_cap, requires_unique_person=excluded.requires_unique_person, requires_unique_group=excluded.requires_unique_group, requires_unique_item=excluded.requires_unique_item, is_extreme_challenge=excluded.is_extreme_challenge, is_enabled=excluded.is_enabled;
insert into public.action_definitions (id,name,tier,hp_cost,xp_percentage,coin_reward,cooldown_minutes,daily_cap,festival_cap,requires_unique_person,requires_unique_group,requires_unique_item,is_extreme_challenge,is_enabled) values ('group_photo','Take a Group Photo With Another Festival Group','rare',0,0.35,25,null,1,null,false,true,false,false,true) on conflict (id) do update set name=excluded.name, tier=excluded.tier, hp_cost=excluded.hp_cost, xp_percentage=excluded.xp_percentage, coin_reward=excluded.coin_reward, cooldown_minutes=excluded.cooldown_minutes, daily_cap=excluded.daily_cap, festival_cap=excluded.festival_cap, requires_unique_person=excluded.requires_unique_person, requires_unique_group=excluded.requires_unique_group, requires_unique_item=excluded.requires_unique_item, is_extreme_challenge=excluded.is_extreme_challenge, is_enabled=excluded.is_enabled;
insert into public.action_definitions (id,name,tier,hp_cost,xp_percentage,coin_reward,cooldown_minutes,daily_cap,festival_cap,requires_unique_person,requires_unique_group,requires_unique_item,is_extreme_challenge,is_enabled) values ('language_phrase','Learn and Test a Phrase in Another Language','rare',0,0.35,25,null,1,null,true,false,false,false,true) on conflict (id) do update set name=excluded.name, tier=excluded.tier, hp_cost=excluded.hp_cost, xp_percentage=excluded.xp_percentage, coin_reward=excluded.coin_reward, cooldown_minutes=excluded.cooldown_minutes, daily_cap=excluded.daily_cap, festival_cap=excluded.festival_cap, requires_unique_person=excluded.requires_unique_person, requires_unique_group=excluded.requires_unique_group, requires_unique_item=excluded.requires_unique_item, is_extreme_challenge=excluded.is_extreme_challenge, is_enabled=excluded.is_enabled;
insert into public.action_definitions (id,name,tier,hp_cost,xp_percentage,coin_reward,cooldown_minutes,daily_cap,festival_cap,requires_unique_person,requires_unique_group,requires_unique_item,is_extreme_challenge,is_enabled) values ('lead_toast','Lead a Toast With Another Festival Group','rare',0,0.35,25,null,1,null,false,true,false,false,true) on conflict (id) do update set name=excluded.name, tier=excluded.tier, hp_cost=excluded.hp_cost, xp_percentage=excluded.xp_percentage, coin_reward=excluded.coin_reward, cooldown_minutes=excluded.cooldown_minutes, daily_cap=excluded.daily_cap, festival_cap=excluded.festival_cap, requires_unique_person=excluded.requires_unique_person, requires_unique_group=excluded.requires_unique_group, requires_unique_item=excluded.requires_unique_item, is_extreme_challenge=excluded.is_extreme_challenge, is_enabled=excluded.is_enabled;
insert into public.action_definitions (id,name,tier,hp_cost,xp_percentage,coin_reward,cooldown_minutes,daily_cap,festival_cap,requires_unique_person,requires_unique_group,requires_unique_item,is_extreme_challenge,is_enabled) values ('receive_item','Receive an Item From Another Person','epic',0,0.6,50,null,1,null,false,false,true,false,true) on conflict (id) do update set name=excluded.name, tier=excluded.tier, hp_cost=excluded.hp_cost, xp_percentage=excluded.xp_percentage, coin_reward=excluded.coin_reward, cooldown_minutes=excluded.cooldown_minutes, daily_cap=excluded.daily_cap, festival_cap=excluded.festival_cap, requires_unique_person=excluded.requires_unique_person, requires_unique_group=excluded.requires_unique_group, requires_unique_item=excluded.requires_unique_item, is_extreme_challenge=excluded.is_extreme_challenge, is_enabled=excluded.is_enabled;
insert into public.consumable_definitions (id,name,rarity,description,max_quantity,usable_from_inventory,image_key) values ('small_health_potion','Small Health Potion','common','Restores 25 HP.',10,true,'small_health_potion') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, description=excluded.description, usable_from_inventory=excluded.usable_from_inventory, image_key=excluded.image_key;
insert into public.consumable_definitions (id,name,rarity,description,max_quantity,usable_from_inventory,image_key) values ('xp_candy','XP Candy','common','Grants 5% of XP needed for the next level.',10,true,'xp_candy') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, description=excluded.description, usable_from_inventory=excluded.usable_from_inventory, image_key=excluded.image_key;
insert into public.consumable_definitions (id,name,rarity,description,max_quantity,usable_from_inventory,image_key) values ('big_health_potion','Big Health Potion','rare','Restores 60 HP.',10,true,'big_health_potion') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, description=excluded.description, usable_from_inventory=excluded.usable_from_inventory, image_key=excluded.image_key;
insert into public.consumable_definitions (id,name,rarity,description,max_quantity,usable_from_inventory,image_key) values ('fortune_ticket','Fortune Ticket','rare','Grants one additional Daily Wheel spin.',10,true,'fortune_ticket') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, description=excluded.description, usable_from_inventory=excluded.usable_from_inventory, image_key=excluded.image_key;
insert into public.consumable_definitions (id,name,rarity,description,max_quantity,usable_from_inventory,image_key) values ('experience_potion','Experience Potion','epic','Grants 30% of XP needed for the next level.',10,true,'experience_potion') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, description=excluded.description, usable_from_inventory=excluded.usable_from_inventory, image_key=excluded.image_key;
insert into public.consumable_definitions (id,name,rarity,description,max_quantity,usable_from_inventory,image_key) values ('discharge_pill','Discharge Pill','epic','Reduces the current Hospital countdown by 20 minutes.',10,false,'discharge_pill') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, description=excluded.description, usable_from_inventory=excluded.usable_from_inventory, image_key=excluded.image_key;
insert into public.consumable_definitions (id,name,rarity,description,max_quantity,usable_from_inventory,image_key) values ('golden_hourglass','Golden Hourglass','legendary','Resets eligible normal action cooldowns.',10,true,'golden_hourglass') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, description=excluded.description, usable_from_inventory=excluded.usable_from_inventory, image_key=excluded.image_key;
insert into public.chaos_card_definitions (id,name,rarity,description,base_damage,max_quantity,self_damage_divisor,image_key) values ('smoke_cigarette','Smoke a Cigarette','common','Smoke a Cigarette',6,10,null,'smoke_cigarette') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, base_damage=excluded.base_damage, self_damage_divisor=excluded.self_damage_divisor, image_key=excluded.image_key;
insert into public.chaos_card_definitions (id,name,rarity,description,base_damage,max_quantity,self_damage_divisor,image_key) values ('double_sip','Double Sip','common','Double Sip',8,10,null,'double_sip') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, base_damage=excluded.base_damage, self_damage_divisor=excluded.self_damage_divisor, image_key=excluded.image_key;
insert into public.chaos_card_definitions (id,name,rarity,description,base_damage,max_quantity,self_damage_divisor,image_key) values ('big_sip','Big Sip','rare','Big Sip',14,10,null,'big_sip') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, base_damage=excluded.base_damage, self_damage_divisor=excluded.self_damage_divisor, image_key=excluded.image_key;
insert into public.chaos_card_definitions (id,name,rarity,description,base_damage,max_quantity,self_damage_divisor,image_key) values ('shot','Shot','rare','Shot',18,10,null,'shot') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, base_damage=excluded.base_damage, self_damage_divisor=excluded.self_damage_divisor, image_key=excluded.image_key;
insert into public.chaos_card_definitions (id,name,rarity,description,base_damage,max_quantity,self_damage_divisor,image_key) values ('jagermeister_shot','Jägermeister Shot','epic','Jägermeister Shot',24,10,null,'jagermeister_shot') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, base_damage=excluded.base_damage, self_damage_divisor=excluded.self_damage_divisor, image_key=excluded.image_key;
insert into public.chaos_card_definitions (id,name,rarity,description,base_damage,max_quantity,self_damage_divisor,image_key) values ('mirror','Mirror','epic','Mirror',32,10,5,'mirror') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, base_damage=excluded.base_damage, self_damage_divisor=excluded.self_damage_divisor, image_key=excluded.image_key;
insert into public.chaos_card_definitions (id,name,rarity,description,base_damage,max_quantity,self_damage_divisor,image_key) values ('finish_your_drink','Finish Your Drink','legendary','Finish Your Drink',37,10,null,'finish_your_drink') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, base_damage=excluded.base_damage, self_damage_divisor=excluded.self_damage_divisor, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('common_regeneration_helmet','Common Regeneration Helmet','common','helmet','regeneration','Common Regeneration Helmet',null,'common_regeneration_helmet') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('common_regeneration_armor','Common Regeneration Armor','common','armor','regeneration','Common Regeneration Armor',null,'common_regeneration_armor') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('common_regeneration_legs','Common Regeneration Legs','common','legs','regeneration','Common Regeneration Legs',null,'common_regeneration_legs') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('common_regeneration_boots','Common Regeneration Boots','common','boots','regeneration','Common Regeneration Boots',null,'common_regeneration_boots') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('common_damage_helmet','Common Damage Helmet','common','helmet','damage','Common Damage Helmet',null,'common_damage_helmet') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('common_damage_armor','Common Damage Armor','common','armor','damage','Common Damage Armor',null,'common_damage_armor') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('common_damage_legs','Common Damage Legs','common','legs','damage','Common Damage Legs',null,'common_damage_legs') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('common_damage_boots','Common Damage Boots','common','boots','damage','Common Damage Boots',null,'common_damage_boots') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('common_dodge_helmet','Common Dodge Helmet','common','helmet','dodge','Common Dodge Helmet',null,'common_dodge_helmet') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('common_dodge_armor','Common Dodge Armor','common','armor','dodge','Common Dodge Armor',null,'common_dodge_armor') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('common_dodge_legs','Common Dodge Legs','common','legs','dodge','Common Dodge Legs',null,'common_dodge_legs') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('common_dodge_boots','Common Dodge Boots','common','boots','dodge','Common Dodge Boots',null,'common_dodge_boots') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('common_potion_helmet','Common Potion Helmet','common','helmet','potion','Common Potion Helmet',null,'common_potion_helmet') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('common_potion_armor','Common Potion Armor','common','armor','potion','Common Potion Armor',null,'common_potion_armor') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('common_potion_legs','Common Potion Legs','common','legs','potion','Common Potion Legs',null,'common_potion_legs') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('common_potion_boots','Common Potion Boots','common','boots','potion','Common Potion Boots',null,'common_potion_boots') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('rare_regeneration_helmet','Rare Regeneration Helmet','rare','helmet','regeneration','Rare Regeneration Helmet',null,'rare_regeneration_helmet') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('rare_regeneration_armor','Rare Regeneration Armor','rare','armor','regeneration','Rare Regeneration Armor',null,'rare_regeneration_armor') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('rare_regeneration_legs','Rare Regeneration Legs','rare','legs','regeneration','Rare Regeneration Legs',null,'rare_regeneration_legs') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('rare_regeneration_boots','Rare Regeneration Boots','rare','boots','regeneration','Rare Regeneration Boots',null,'rare_regeneration_boots') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('rare_damage_helmet','Rare Damage Helmet','rare','helmet','damage','Rare Damage Helmet',null,'rare_damage_helmet') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('rare_damage_armor','Rare Damage Armor','rare','armor','damage','Rare Damage Armor',null,'rare_damage_armor') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('rare_damage_legs','Rare Damage Legs','rare','legs','damage','Rare Damage Legs',null,'rare_damage_legs') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('rare_damage_boots','Rare Damage Boots','rare','boots','damage','Rare Damage Boots',null,'rare_damage_boots') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('rare_protection_helmet','Rare Protection Helmet','rare','helmet','protection','Rare Protection Helmet',null,'rare_protection_helmet') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('rare_protection_armor','Rare Protection Armor','rare','armor','protection','Rare Protection Armor',null,'rare_protection_armor') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('rare_protection_legs','Rare Protection Legs','rare','legs','protection','Rare Protection Legs',null,'rare_protection_legs') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('rare_protection_boots','Rare Protection Boots','rare','boots','protection','Rare Protection Boots',null,'rare_protection_boots') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('rare_hospital_helmet','Rare Hospital Helmet','rare','helmet','hospital','Rare Hospital Helmet',null,'rare_hospital_helmet') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('rare_hospital_armor','Rare Hospital Armor','rare','armor','hospital','Rare Hospital Armor',null,'rare_hospital_armor') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('rare_hospital_legs','Rare Hospital Legs','rare','legs','hospital','Rare Hospital Legs',null,'rare_hospital_legs') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('rare_hospital_boots','Rare Hospital Boots','rare','boots','hospital','Rare Hospital Boots',null,'rare_hospital_boots') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('epic_regeneration_helmet','Epic Regeneration Helmet','epic','helmet','regeneration','Epic Regeneration Helmet',4,'epic_regeneration_helmet') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('epic_regeneration_armor','Epic Regeneration Armor','epic','armor','regeneration','Epic Regeneration Armor',4,'epic_regeneration_armor') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('epic_regeneration_legs','Epic Regeneration Legs','epic','legs','regeneration','Epic Regeneration Legs',4,'epic_regeneration_legs') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('epic_regeneration_boots','Epic Regeneration Boots','epic','boots','regeneration','Epic Regeneration Boots',4,'epic_regeneration_boots') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('epic_damage_helmet','Epic Damage Helmet','epic','helmet','damage','Epic Damage Helmet',4,'epic_damage_helmet') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('epic_damage_armor','Epic Damage Armor','epic','armor','damage','Epic Damage Armor',4,'epic_damage_armor') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('epic_damage_legs','Epic Damage Legs','epic','legs','damage','Epic Damage Legs',4,'epic_damage_legs') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('epic_damage_boots','Epic Damage Boots','epic','boots','damage','Epic Damage Boots',4,'epic_damage_boots') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('epic_gold_helmet','Epic Gold Helmet','epic','helmet','gold','Epic Gold Helmet',4,'epic_gold_helmet') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('epic_gold_armor','Epic Gold Armor','epic','armor','gold','Epic Gold Armor',4,'epic_gold_armor') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('epic_gold_legs','Epic Gold Legs','epic','legs','gold','Epic Gold Legs',4,'epic_gold_legs') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('epic_gold_boots','Epic Gold Boots','epic','boots','gold','Epic Gold Boots',4,'epic_gold_boots') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('epic_chest_helmet','Epic Chest Helmet','epic','helmet','chest','Epic Chest Helmet',4,'epic_chest_helmet') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('epic_chest_armor','Epic Chest Armor','epic','armor','chest','Epic Chest Armor',4,'epic_chest_armor') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('epic_chest_legs','Epic Chest Legs','epic','legs','chest','Epic Chest Legs',4,'epic_chest_legs') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('epic_chest_boots','Epic Chest Boots','epic','boots','chest','Epic Chest Boots',4,'epic_chest_boots') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('legendary_regeneration_helmet','Legendary Regeneration Helmet','legendary','helmet','regeneration','Legendary Regeneration Helmet',1,'legendary_regeneration_helmet') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('legendary_regeneration_armor','Legendary Regeneration Armor','legendary','armor','regeneration','Legendary Regeneration Armor',1,'legendary_regeneration_armor') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('legendary_regeneration_legs','Legendary Regeneration Legs','legendary','legs','regeneration','Legendary Regeneration Legs',1,'legendary_regeneration_legs') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('legendary_regeneration_boots','Legendary Regeneration Boots','legendary','boots','regeneration','Legendary Regeneration Boots',1,'legendary_regeneration_boots') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('legendary_damage_helmet','Legendary Damage Helmet','legendary','helmet','damage','Legendary Damage Helmet',1,'legendary_damage_helmet') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('legendary_damage_armor','Legendary Damage Armor','legendary','armor','damage','Legendary Damage Armor',1,'legendary_damage_armor') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('legendary_damage_legs','Legendary Damage Legs','legendary','legs','damage','Legendary Damage Legs',1,'legendary_damage_legs') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('legendary_damage_boots','Legendary Damage Boots','legendary','boots','damage','Legendary Damage Boots',1,'legendary_damage_boots') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('legendary_thorns_helmet','Legendary Thorns Helmet','legendary','helmet','thorns','Legendary Thorns Helmet',1,'legendary_thorns_helmet') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('legendary_thorns_armor','Legendary Thorns Armor','legendary','armor','thorns','Legendary Thorns Armor',1,'legendary_thorns_armor') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('legendary_thorns_legs','Legendary Thorns Legs','legendary','legs','thorns','Legendary Thorns Legs',1,'legendary_thorns_legs') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('legendary_thorns_boots','Legendary Thorns Boots','legendary','boots','thorns','Legendary Thorns Boots',1,'legendary_thorns_boots') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('legendary_phoenix_helmet','Legendary Phoenix Helmet','legendary','helmet','phoenix','Legendary Phoenix Helmet',1,'legendary_phoenix_helmet') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('legendary_phoenix_armor','Legendary Phoenix Armor','legendary','armor','phoenix','Legendary Phoenix Armor',1,'legendary_phoenix_armor') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('legendary_phoenix_legs','Legendary Phoenix Legs','legendary','legs','phoenix','Legendary Phoenix Legs',1,'legendary_phoenix_legs') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;
insert into public.equipment_definitions (id,name,rarity,slot,set_key,description,global_copy_limit,image_key) values ('legendary_phoenix_boots','Legendary Phoenix Boots','legendary','boots','phoenix','Legendary Phoenix Boots',1,'legendary_phoenix_boots') on conflict (id) do update set name=excluded.name, rarity=excluded.rarity, slot=excluded.slot, set_key=excluded.set_key, global_copy_limit=excluded.global_copy_limit, image_key=excluded.image_key;

commit;
