"use client";
import Image from "next/image";
import {useEffect,useMemo,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {getAsset} from "@/lib/assets/registry";
const title=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const descriptions:Record<string,string>={small_health_potion:"Restores 25 HP.",xp_candy:"Grants 5% of the XP needed for your next level.",big_health_potion:"Restores 60 HP.",fortune_ticket:"Grants one free Daily Wheel spin.",experience_potion:"Grants 30% of the XP needed for your next level.",discharge_pill:"Reduces remaining Hospital time by 20 minutes.",golden_hourglass:"Resets eligible active Action cooldowns."};
function Art({category,imageKey,name}:{category:"equipment"|"consumables"|"chaosCards",imageKey:string,name:string}){const asset=getAsset(category,imageKey);return asset?<Image src={asset.path} alt={name} width={220} height={220} style={{width:"100%",height:"auto",objectFit:"contain"}}/>:null}
export function InventoryScreen({model}:{model:any}){
 const[tab,setTab]=useState<"equipment"|"consumables"|"chaos">("equipment"),[message,setMessage]=useState<string|null>(null),[selected,setSelected]=useState<any>(null),[pending,setPending]=useState(false),[rarity,setRarity]=useState("all"),[slot,setSlot]=useState("all"),[effect,setEffect]=useState("all"),[wear,setWear]=useState("all"),router=useRouter(),retryKey=useRef<string|null>(null);
 useEffect(()=>{const refresh=()=>router.refresh();window.addEventListener("focus",refresh);window.addEventListener("online",refresh);return()=>{window.removeEventListener("focus",refresh);window.removeEventListener("online",refresh)}},[router]);
 const equipment=useMemo(()=>model.equipment.filter((i:any)=>(rarity==="all"||i.definition?.rarity===rarity)&&(slot==="all"||i.definition?.slot===slot)&&(effect==="all"||i.definition?.effectKind===effect)&&(wear==="all"||(wear==="equipped")===i.equipped)),[model,rarity,slot,effect,wear]);
 async function send(body:any,success:string){if(pending)return;setPending(true);setMessage(null);retryKey.current??=crypto.randomUUID();const response=await fetch("/api/inventory",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,idempotencyKey:retryKey.current})});const result=await response.json();if(response.ok){retryKey.current=null;setSelected(null);setMessage(success);router.refresh()}else setMessage(result.message);setPending(false);}
 function equipmentCommand(item:any){const kind=item.equipped?"unequip":"equip",replacement=kind==="equip"?model.equipment.find((v:any)=>v.equipped&&v.slot===item.definition.slot):null;return send(kind==="equip"?{command:kind,itemId:item.inventoryItemId,replaceItemId:replacement?.inventoryItemId??null}:{command:kind,itemId:item.inventoryItemId},"Equipment updated.")}
 const now=Date.parse(model.serverNow);
 return <section className="stack"><div><span className="eyebrow">Run inventory</span><h1>Inventory</h1><p className="muted">Equipment cooldowns belong to each individual copy.</p></div><div className="pool-actions">{[["equipment","Equipment"],["consumables","Consumables"],["chaos","Chaos Cards"]].map(([id,label])=><button key={id} className={tab===id?"button":"button secondary"} onClick={()=>setTab(id as any)}>{label}</button>)}</div>{message&&<p role="status">{message}</p>}
 {tab==="equipment"&&<><div className="pool-actions"><select aria-label="Rarity" value={rarity} onChange={e=>setRarity(e.target.value)}><option value="all">All rarities</option>{["common","rare","epic","legendary"].map(v=><option key={v}>{v}</option>)}</select><select aria-label="Slot" value={slot} onChange={e=>setSlot(e.target.value)}><option value="all">All slots</option>{["helmet","armor","legs","boots"].map(v=><option key={v}>{v}</option>)}</select><select aria-label="Effect" value={effect} onChange={e=>setEffect(e.target.value)}><option value="all">All effects</option>{[...new Set(model.equipment.map((i:any)=>i.definition?.effectKind).filter(Boolean))].map((v:any)=><option key={v}>{v}</option>)}</select><select aria-label="Equipped state" value={wear} onChange={e=>setWear(e.target.value)}><option value="all">Equipped or not</option><option value="equipped">Equipped</option><option value="unequipped">Unequipped</option></select></div><div className="action-grid">{equipment.length===0?<div className="card">No matching Equipment.</div>:equipment.map((item:any)=>{const cooling=Date.parse(item.cooldownEndsAt)>now;return <article className="card stack compact" key={item.inventoryItemId}><Art category="equipment" imageKey={item.definition.imageKey} name={item.definition.name}/><span className="badge">{item.definition.rarity}</span><h3>{item.definition.name}</h3><p>{title(item.definition.effectKind)}: {item.definition.effectValue} {item.definition.effectKind==="gold"?"coins / 2 effective hours":""}</p><p className="muted">{item.equipped?`Equipped: ${title(item.slot)}`:"Unequipped"} · {title(item.definition.slot)} · set bonus {item.definition.fullSetBonus}</p>{cooling&&<p className="muted">Cooldown until {new Date(item.cooldownEndsAt).toLocaleTimeString()}</p>}<button className="button" disabled={pending||cooling} onClick={()=>setSelected({type:"equipment",item})}>Inspect</button></article>})}</div></>}
 {tab==="consumables"&&<div className="action-grid">{model.consumables.filter((i:any)=>i.quantity>0).length===0?<div className="card">No Consumables owned.</div>:model.consumables.filter((i:any)=>i.quantity>0).map((i:any)=><article className="card stack compact" key={i.id}><Art category="consumables" imageKey={i.id} name={i.name}/><span className="badge">{i.rarity}</span><h3>{i.name}</h3><strong>×{i.quantity}</strong><button className="button" disabled={pending} onClick={()=>setSelected({type:"consumable",item:i})}>Inspect</button></article>)}</div>}
 {tab==="chaos"&&<div className="action-grid">{model.chaosCards.filter((i:any)=>i.quantity>0).length===0?<div className="card">No Chaos Cards owned.</div>:model.chaosCards.filter((i:any)=>i.quantity>0).map((i:any)=><article className="card stack compact" key={i.id}><Art category="chaosCards" imageKey={i.id} name={i.name}/><span className="badge">{i.rarity}</span><h3>{i.name}</h3><strong>×{i.quantity}</strong><button className="button" onClick={()=>setSelected({type:"chaos",item:i})}>Inspect</button></article>)}</div>}
 {selected&&<div role="dialog" aria-modal="true" className="card stack"><Art category={selected.type==="equipment"?"equipment":selected.type==="chaos"?"chaosCards":"consumables"} imageKey={selected.type==="equipment"?selected.item.definition.imageKey:selected.item.id} name={selected.type==="equipment"?selected.item.definition.name:selected.item.name}/><h2>{selected.type==="equipment"?selected.item.definition.name:selected.item.name}</h2><p>{selected.type==="equipment"?`${title(selected.item.definition.effectKind)} ${selected.item.definition.effectValue}`:selected.type==="chaos"?"Inspect only until Handoff 5.":descriptions[selected.item.id]}</p>{selected.type==="consumable"&&<p>Quantity: {selected.item.quantity}</p>}<div className="pool-actions"><button className="button secondary" disabled={pending} onClick={()=>setSelected(null)}>Cancel</button>{selected.type==="equipment"&&<button className="button" disabled={pending||Date.parse(selected.item.cooldownEndsAt)>now} onClick={()=>equipmentCommand(selected.item)}>{selected.item.equipped?"Unequip":"Equip"}</button>}{selected.type==="consumable"&&selected.item.id!=="discharge_pill"&&<button className="button" disabled={pending} onClick={()=>send({command:"use_consumable",itemId:selected.item.id},"Consumable used.")}>Use</button>}{selected.type==="consumable"&&selected.item.id==="discharge_pill"&&<span className="muted">Use this from the Hospital screen.</span>}</div></div>}
 </section>
}
