begin;

alter table public.level_xp_thresholds add column requirement integer;
update public.level_xp_thresholds t set requirement=n.total_xp-t.total_xp from public.level_xp_thresholds n where n.level=t.level+1;
alter table public.level_xp_thresholds add constraint level_xp_thresholds_requirement_check check(requirement is null or requirement>0);

create type public.action_tier as enum ('common','rare','epic','legendary');
create type public.action_submission_status as enum ('pending','accepted','rejected','expired','cancelled');
create type public.action_cancellation_reason as enum ('owner_hospitalized','run_ended','admin_cancelled');

create table public.action_definitions(
 id text primary key check(id=lower(id) and id~'^[a-z0-9_]+$'), name text not null, short_description text not null,
 category text not null, tier public.action_tier not null, xp_basis_points integer not null check(xp_basis_points>0),
 coin_reward integer not null check(coin_reward>=0), hp_cost integer not null check(hp_cost>=0), cooldown_seconds integer check(cooldown_seconds>0),
 daily_cap integer check(daily_cap>0), festival_cap integer check(festival_cap>0), distinct_reference_kind text check(distinct_reference_kind in('person','group','item')),
 is_enabled boolean not null, is_extreme_challenge boolean not null default false, challenge_text text,
 image_key text not null, hourglass_resettable boolean not null default false,
 check(not is_extreme_challenge or (id='extreme_challenge' and daily_cap=1))
);
create index action_definitions_enabled_tier_idx on public.action_definitions(is_enabled,tier);

create table public.action_submissions(
 id uuid primary key default gen_random_uuid(), game_run_id uuid not null references public.game_runs(id), owner_player_id uuid not null references public.players(id),
 action_id text not null references public.action_definitions(id), status public.action_submission_status not null default 'pending',
 submitted_at timestamptz not null default clock_timestamp(), expires_at timestamptz not null,
 validator_player_id uuid references public.players(id), accepted_at timestamptz, rejected_at timestamptz, resolved_at timestamptz,
 cancellation_reason public.action_cancellation_reason, created_by_idempotency_key uuid not null,
 check(expires_at>submitted_at), check(owner_player_id is distinct from validator_player_id),
 check((status='pending' and validator_player_id is null and resolved_at is null and cancellation_reason is null) or
       (status='accepted' and validator_player_id is not null and accepted_at is not null and resolved_at=accepted_at and cancellation_reason is null) or
       (status='rejected' and validator_player_id is not null and rejected_at is not null and resolved_at=rejected_at and cancellation_reason is null) or
       (status='expired' and validator_player_id is null and resolved_at is not null and cancellation_reason is null) or
       (status='cancelled' and resolved_at is not null and cancellation_reason is not null))
);
create unique index action_submissions_pending_action_idx on public.action_submissions(game_run_id,owner_player_id,action_id) where status='pending';
create unique index action_submissions_submit_key_idx on public.action_submissions(game_run_id,owner_player_id,created_by_idempotency_key);
create index action_submissions_pool_idx on public.action_submissions(game_run_id,status,submitted_at) where status='pending';
create index action_submissions_owner_pending_idx on public.action_submissions(game_run_id,owner_player_id) where status='pending';
create index action_submissions_expiry_idx on public.action_submissions(expires_at) where status='pending';

create table public.action_usages(
 id uuid primary key default gen_random_uuid(),game_run_id uuid not null,player_id uuid not null,action_id text not null references public.action_definitions(id),
 submission_id uuid not null unique references public.action_submissions(id),accepted_at timestamptz not null,festival_day_key date not null,
 foreign key(game_run_id,player_id) references public.player_run_states(game_run_id,player_id)
);
create index action_usages_daily_idx on public.action_usages(game_run_id,player_id,action_id,festival_day_key);
create index action_usages_festival_idx on public.action_usages(game_run_id,player_id,action_id);
create table public.action_cooldowns(game_run_id uuid not null,player_id uuid not null,action_id text not null references public.action_definitions(id),cooldown_ends_at timestamptz not null,source_submission_id uuid not null references public.action_submissions(id),updated_at timestamptz not null default clock_timestamp(),primary key(game_run_id,player_id,action_id),foreign key(game_run_id,player_id) references public.player_run_states(game_run_id,player_id));
create index action_cooldowns_due_idx on public.action_cooldowns(game_run_id,player_id,cooldown_ends_at);
create table public.daily_quest_progress(game_run_id uuid not null,player_id uuid not null,festival_day_key date not null,accepted_actions integer not null default 0 check(accepted_actions>=0),successful_validations integer not null default 0 check(successful_validations>=0),created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default clock_timestamp(),primary key(game_run_id,player_id,festival_day_key),foreign key(game_run_id,player_id) references public.player_run_states(game_run_id,player_id));
create index daily_quest_progress_lookup_idx on public.daily_quest_progress(game_run_id,player_id,festival_day_key);
create table public.daily_quest_distinct_actions(game_run_id uuid not null,player_id uuid not null,festival_day_key date not null,action_id text not null references public.action_definitions(id),created_at timestamptz not null default clock_timestamp(),primary key(game_run_id,player_id,festival_day_key,action_id),foreign key(game_run_id,player_id,festival_day_key) references public.daily_quest_progress(game_run_id,player_id,festival_day_key));
create table public.daily_quest_completions(id uuid primary key default gen_random_uuid(),game_run_id uuid not null,player_id uuid not null,festival_day_key date not null,quest_id text not null check(quest_id in('easy_accepted_5','easy_validations_10','easy_variety_5','medium_accepted_10','medium_validations_15','hard_daily_mastery')),xp_granted integer not null,coins_granted integer not null,completed_at timestamptz not null default clock_timestamp(),unique(game_run_id,player_id,festival_day_key,quest_id),foreign key(game_run_id,player_id,festival_day_key) references public.daily_quest_progress(game_run_id,player_id,festival_day_key));
create table public.hospital_stays(id uuid primary key default gen_random_uuid(),game_run_id uuid not null,player_id uuid not null,source_submission_id uuid references public.action_submissions(id),started_at timestamptz not null, hospital_until timestamptz not null,released_at timestamptz,xp_lost integer not null check(xp_lost>=0),foreign key(game_run_id,player_id) references public.player_run_states(game_run_id,player_id),check(hospital_until>started_at));
create unique index hospital_stays_active_idx on public.hospital_stays(game_run_id,player_id) where released_at is null;

insert into public.action_definitions(id,name,short_description,category,tier,xp_basis_points,coin_reward,hp_cost,cooldown_seconds,daily_cap,festival_cap,distinct_reference_kind,is_enabled,is_extreme_challenge,image_key,hourglass_resettable) values
('smoke_cigarette','Smoke a Cigarette','Smoke a cigarette or an approved substitute.','hp_cost','common',1500,10,6,600,null,null,null,true,false,'smoke_cigarette',true),
('drink_beer','Drink a Beer','Drink a beer or an approved substitute.','hp_cost','common',1500,10,10,600,null,null,null,true,false,'drink_beer',true),
('drink_strong_mixed_drink','Drink a Strong Mixed Drink','Drink a strong mixed drink or approved substitute.','hp_cost','rare',3500,25,14,600,null,null,null,true,false,'drink_strong_mixed_drink',true),
('take_shot','Take a Shot','Take a shot or approved substitute.','hp_cost','rare',3500,25,18,600,null,null,null,true,false,'take_shot',true),
('take_jagermeister_shot','Take a Jägermeister Shot','Take a Jägermeister shot or approved substitute.','hp_cost','epic',6000,50,24,600,null,null,null,true,false,'take_jagermeister_shot',true),
('smoke_joint','Smoke a Joint','Smoke a joint or approved substitute.','hp_cost','epic',6000,50,30,600,null,null,null,true,false,'smoke_joint',true),
('finish_your_drink','Finish Your Drink','Finish your drink or approved substitute.','hp_cost','legendary',9000,100,37,600,null,null,null,true,false,'finish_your_drink',true),
('extreme_challenge','Extreme Challenge','Unavailable until configured.','festival_special','legendary',15000,150,60,null,1,null,null,false,true,'extreme_challenge',false),
('push_ups_20','20 Push-ups','Complete 20 push-ups.','physical_recovery','common',1500,10,0,3600,5,null,null,true,false,'push_ups_20',true),
('squats_40','40 Squats','Complete 40 squats.','physical_recovery','common',1500,10,0,3600,5,null,null,true,false,'squats_40',true),
('cold_shower','Cold Shower','Take a cold shower.','physical_recovery','common',1500,10,0,14400,2,null,null,true,false,'cold_shower',true),
('pay_for_shower','Pay for a Shower','Pay for and take a shower.','physical_recovery','rare',3500,25,0,null,1,null,null,true,false,'pay_for_shower',false),
('find_someone_you_know','Find Someone You Know','Find a different person you know.','social','common',1500,10,0,null,null,null,'person',true,false,'find_someone_you_know',false),
('talk_to_stranger_20_minutes','Talk to a Stranger for 20+ Minutes','Talk for at least 20 minutes.','social','rare',3500,25,0,null,2,null,'person',true,false,'talk_to_stranger_20_minutes',false),
('find_catalan_people','Find Catalan People','Meet Catalan people.','social','rare',3500,25,0,null,1,null,'group',true,false,'find_catalan_people',false),
('make_out_with_someone','Make Out With Someone','Voluntary and consensual.','social','epic',6000,50,0,null,1,null,'person',true,false,'make_out_with_someone',false),
('have_sex_with_someone','Have Sex With Someone','Voluntary and consensual.','social','legendary',9000,100,0,null,null,1,'person',true,false,'have_sex_with_someone',false),
('get_permanent_tattoo','Get a Permanent Tattoo','Get a permanent tattoo.','social','legendary',9000,100,0,null,null,1,null,true,false,'get_permanent_tattoo',false),
('take_group_photo_other_festival_group','Take a Group Photo With Another Festival Group','Take a group photo with another festival group.','festival_special','rare',3500,25,0,null,1,null,'group',true,false,'action_fallback',false),
('learn_and_test_phrase_other_language','Learn and Test a Phrase in Another Language','Learn and test a phrase.','festival_special','rare',3500,25,0,null,1,null,'person',true,false,'action_fallback',false),
('lead_toast_other_festival_group','Lead a Toast With Another Festival Group','Lead a toast with another group.','festival_special','rare',3500,25,0,null,1,null,'group',true,false,'action_fallback',false),
('receive_item_from_another_person','Receive an Item From Another Person','Receive a freely given or lent item.','festival_special','epic',6000,50,0,null,1,null,'item',true,false,'action_fallback',false);

create or replace function public.action_day_key(p_at timestamptz) returns date language sql immutable set search_path=public,pg_temp as $$ select case when (p_at at time zone 'Europe/Berlin')::date='2026-07-20'::date then '2026-07-19'::date else (p_at at time zone 'Europe/Berlin')::date end $$;
create or replace function public.action_assert_live(p_run uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$ declare v public.game_runs%rowtype; begin select gr.* into v from public.active_game_run agr join public.game_runs gr on gr.id=agr.game_run_id where agr.game_run_id=p_run for update of gr;if not found then raise exception 'STALE_RUN';end if;if v.phase<>'live' or clock_timestamp()>=v.normal_gameplay_ends_at then raise exception 'PHASE_BLOCKED';end if;end $$;

create or replace function public.submit_action(p_actor uuid,p_run uuid,p_action text,p_idempotency_key uuid,p_request_hash text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_state public.player_run_states%rowtype;v_def public.action_definitions%rowtype;v_existing public.idempotency_records%rowtype;v_id uuid;v_now timestamptz:=clock_timestamp();v_day date;v_result jsonb;
begin perform public.action_assert_live(p_run);if p_request_hash!~'^[0-9a-f]{64}$' then raise exception 'VALIDATION';end if;insert into public.idempotency_records(actor_player_id,game_run_id,command_name,idempotency_key,request_hash,expires_at)values(p_actor,p_run,'submit_action',p_idempotency_key,p_request_hash,v_now+interval '24 hours')on conflict do nothing;select ir.* into v_existing from public.idempotency_records ir where ir.actor_player_id=p_actor and ir.command_name='submit_action' and ir.idempotency_key=p_idempotency_key for update;if v_existing.request_hash<>p_request_hash then raise exception 'IDEMPOTENCY_CONFLICT';end if;if v_existing.status='completed' then return v_existing.result;end if;
select prs.* into v_state from public.player_run_states prs join public.players p on p.id=prs.player_id where prs.game_run_id=p_run and prs.player_id=p_actor and p.status='active' for update of prs;if not found then raise exception 'FORBIDDEN';end if;if v_state.gameplay_status='hospitalized' then raise exception 'HOSPITALIZED';end if;if v_state.gameplay_status<>'active' then raise exception 'STATUS_BLOCKED';end if;select ad.* into v_def from public.action_definitions ad where ad.id=p_action;if not found or not v_def.is_enabled or(v_def.is_extreme_challenge and v_def.challenge_text is null)then raise exception 'ACTION_UNAVAILABLE';end if;
update public.action_submissions s set status='expired',resolved_at=v_now where s.game_run_id=p_run and s.owner_player_id=p_actor and s.status='pending' and s.expires_at<=v_now;if(select count(*) from public.action_submissions s where s.game_run_id=p_run and s.owner_player_id=p_actor and s.status='pending')>=3 then raise exception 'PENDING_LIMIT';end if;if exists(select 1 from public.action_submissions s where s.game_run_id=p_run and s.owner_player_id=p_actor and s.action_id=p_action and s.status='pending')then raise exception 'ACTION_PENDING';end if;if exists(select 1 from public.action_cooldowns c where c.game_run_id=p_run and c.player_id=p_actor and c.action_id=p_action and c.cooldown_ends_at>v_now)then raise exception 'COOLDOWN';end if;v_day:=public.action_day_key(v_now);if v_def.daily_cap is not null and(select count(*) from public.action_usages u where u.game_run_id=p_run and u.player_id=p_actor and u.action_id=p_action and u.festival_day_key=v_day)>=v_def.daily_cap then raise exception 'DAILY_CAP';end if;if v_def.festival_cap is not null and(select count(*) from public.action_usages u where u.game_run_id=p_run and u.player_id=p_actor and u.action_id=p_action)>=v_def.festival_cap then raise exception 'FESTIVAL_CAP';end if;
insert into public.action_submissions(game_run_id,owner_player_id,action_id,submitted_at,expires_at,created_by_idempotency_key)values(p_run,p_actor,p_action,v_now,v_now+interval '2 hours',p_idempotency_key)returning id into v_id;perform public.core_record_event(p_run,p_actor,'action_submitted',jsonb_build_object('submissionId',v_id,'actionId',p_action));v_result:=jsonb_build_object('submissionId',v_id,'actionId',p_action,'status','pending','submittedAt',v_now,'expiresAt',v_now+interval '2 hours');update public.idempotency_records ir set status='completed',result=v_result,completed_at=clock_timestamp()where ir.actor_player_id=p_actor and ir.command_name='submit_action' and ir.idempotency_key=p_idempotency_key;return v_result;end $$;

create or replace function public.reject_action_submission(p_actor uuid,p_run uuid,p_submission uuid,p_idempotency_key uuid,p_request_hash text)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare v_s public.action_submissions%rowtype;v_state public.player_run_states%rowtype;v_now timestamptz:=clock_timestamp();begin perform public.action_assert_live(p_run);select s.* into v_s from public.action_submissions s where s.id=p_submission and s.game_run_id=p_run for update;if not found then raise exception 'NOT_FOUND';end if;if v_s.status<>'pending' then return jsonb_build_object('submissionId',v_s.id,'status',v_s.status);end if;if v_s.expires_at<=v_now then update public.action_submissions s set status='expired',resolved_at=v_now where s.id=p_submission;return jsonb_build_object('submissionId',p_submission,'status','expired');end if;if v_s.owner_player_id=p_actor then raise exception 'FORBIDDEN';end if;select prs.* into v_state from public.player_run_states prs where prs.game_run_id=p_run and prs.player_id=p_actor for update;if not found or v_state.gameplay_status<>'active' then raise exception 'STATUS_BLOCKED';end if;update public.action_submissions s set status='rejected',validator_player_id=p_actor,rejected_at=v_now,resolved_at=v_now where s.id=p_submission;perform public.core_record_event(p_run,v_s.owner_player_id,'action_rejected',jsonb_build_object('submissionId',p_submission));return jsonb_build_object('submissionId',p_submission,'status','rejected','rejectedAt',v_now);end $$;

create or replace function public.cancel_pending_actions_for_player(p_run uuid,p_player uuid,p_reason public.action_cancellation_reason)returns integer language plpgsql security definer set search_path=public,pg_temp as $$declare v_count integer;begin with changed as(update public.action_submissions s set status='cancelled',cancellation_reason=p_reason,resolved_at=clock_timestamp()where s.game_run_id=p_run and s.owner_player_id=p_player and s.status='pending' returning 1)select count(*) into v_count from changed;if v_count>0 then perform public.core_record_event(p_run,p_player,'action_cancelled',jsonb_build_object('reason',p_reason,'count',v_count));end if;return v_count;end $$;

create or replace function public.action_complete_eligible_quests(p_run uuid,p_player uuid,p_day date,p_at timestamptz)returns text[] language plpgsql security definer set search_path=public,pg_temp as $$
declare v_progress public.daily_quest_progress%rowtype;v_distinct integer;v_quest text;v_xp_bp integer;v_coins integer;v_need integer;v_level integer;v_mult numeric;v_xp integer;v_done text[]:='{}';
begin select q.* into v_progress from public.daily_quest_progress q where q.game_run_id=p_run and q.player_id=p_player and q.festival_day_key=p_day for update;select count(*) into v_distinct from public.daily_quest_distinct_actions d where d.game_run_id=p_run and d.player_id=p_player and d.festival_day_key=p_day;
for v_quest,v_xp_bp,v_coins in values('easy_accepted_5',8000,15),('easy_validations_10',8000,15),('easy_variety_5',8000,15),('medium_accepted_10',14000,30),('medium_validations_15',14000,30),('hard_daily_mastery',23000,95) loop
 if (v_quest='easy_accepted_5' and v_progress.accepted_actions>=5)or(v_quest='easy_validations_10' and v_progress.successful_validations>=10)or(v_quest='easy_variety_5' and v_distinct>=5)or(v_quest='medium_accepted_10' and v_progress.accepted_actions>=10)or(v_quest='medium_validations_15' and v_progress.successful_validations>=15)or(v_quest='hard_daily_mastery' and v_progress.accepted_actions>=15 and v_progress.successful_validations>=20 and v_distinct>=7)then
  if not exists(select 1 from public.daily_quest_completions c where c.game_run_id=p_run and c.player_id=p_player and c.festival_day_key=p_day and c.quest_id=v_quest)then
   select prs.current_level into v_level from public.player_run_states prs where prs.game_run_id=p_run and prs.player_id=p_player for update;select t.requirement into v_need from public.level_xp_thresholds t where t.level=v_level;v_mult:=case when v_level<=10 then 1 when v_level<=20 then .8 when v_level<=30 then .65 else .5 end;v_xp:=case when v_need is null then 0 else ceil(v_need*(v_xp_bp/10000.0)*v_mult)end;
   perform public.core_mutate_xp(p_player,p_run,p_player,v_xp,'daily_quest',p_day::text||':'||v_quest,gen_random_uuid(),encode(digest('quest-xp:'||p_run::text||':'||p_player::text||':'||p_day::text||':'||v_quest,'sha256'),'hex'));perform public.core_change_coins(p_player,p_run,p_player,v_coins,'daily_quest',p_day::text||':'||v_quest,gen_random_uuid(),encode(digest('quest-coins:'||p_run::text||':'||p_player::text||':'||p_day::text||':'||v_quest,'sha256'),'hex'));
   insert into public.daily_quest_completions(game_run_id,player_id,festival_day_key,quest_id,xp_granted,coins_granted,completed_at)values(p_run,p_player,p_day,v_quest,v_xp,v_coins,p_at);perform public.core_record_event(p_run,p_player,'daily_quest_completed',jsonb_build_object('questId',v_quest,'xp',v_xp,'coins',v_coins));v_done:=array_append(v_done,v_quest);
  end if;
 end if;
end loop;return v_done;end $$;

-- Acceptance owns all effects in one transaction. The canonical Handoff 2 tables,
-- threshold function and reward ledgers are reused; no client values enter rewards.
create or replace function public.accept_action_submission(p_actor uuid,p_run uuid,p_submission uuid,p_idempotency_key uuid,p_request_hash text)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_s public.action_submissions%rowtype;v_d public.action_definitions%rowtype;v_owner public.player_run_states%rowtype;v_validator public.player_run_states%rowtype;v_existing public.idempotency_records%rowtype;v_now timestamptz:=clock_timestamp();v_day date;v_need integer;v_mult numeric;v_xp integer;v_penalty integer:=0;v_cancelled integer:=0;v_result jsonb;
begin perform public.action_assert_live(p_run);select s.* into v_s from public.action_submissions s where s.id=p_submission and s.game_run_id=p_run for update;if not found then raise exception 'NOT_FOUND';end if;if v_s.status<>'pending' then return jsonb_build_object('submissionId',v_s.id,'status',v_s.status);end if;if v_s.expires_at<=v_now then update public.action_submissions s set status='expired',resolved_at=v_now where s.id=p_submission;return jsonb_build_object('submissionId',p_submission,'status','expired');end if;if v_s.owner_player_id=p_actor then raise exception 'FORBIDDEN';end if;
select prs.* into v_owner from public.player_run_states prs where prs.game_run_id=p_run and prs.player_id=v_s.owner_player_id for update;select prs.* into v_validator from public.player_run_states prs where prs.game_run_id=p_run and prs.player_id=p_actor for update;if v_owner.gameplay_status<>'active' or v_validator.gameplay_status<>'active' then raise exception 'STATUS_BLOCKED';end if;if exists(select 1 from public.action_submissions x where x.game_run_id=p_run and x.owner_player_id=v_s.owner_player_id and x.status='accepted' and x.validator_player_id=p_actor and not exists(select 1 from public.action_submissions y where y.game_run_id=p_run and y.owner_player_id=v_s.owner_player_id and y.status='accepted' and y.accepted_at>x.accepted_at) order by x.accepted_at desc limit 1)then raise exception 'CONSECUTIVE_VALIDATOR';end if;select ad.* into v_d from public.action_definitions ad where ad.id=v_s.action_id;if not v_d.is_enabled then raise exception 'ACTION_UNAVAILABLE';end if;v_day:=public.action_day_key(v_now);if exists(select 1 from public.action_cooldowns c where c.game_run_id=p_run and c.player_id=v_s.owner_player_id and c.action_id=v_s.action_id and c.cooldown_ends_at>v_now)then raise exception 'COOLDOWN';end if;if v_d.daily_cap is not null and(select count(*) from public.action_usages u where u.game_run_id=p_run and u.player_id=v_s.owner_player_id and u.action_id=v_s.action_id and u.festival_day_key=v_day)>=v_d.daily_cap then raise exception 'DAILY_CAP';end if;if v_d.festival_cap is not null and(select count(*) from public.action_usages u where u.game_run_id=p_run and u.player_id=v_s.owner_player_id and u.action_id=v_s.action_id)>=v_d.festival_cap then raise exception 'FESTIVAL_CAP';end if;
update public.action_submissions s set status='accepted',validator_player_id=p_actor,accepted_at=v_now,resolved_at=v_now where s.id=p_submission;select requirement into v_need from public.level_xp_thresholds where level=v_owner.current_level;v_mult:=case when v_owner.current_level<=10 then 1 when v_owner.current_level<=20 then .8 when v_owner.current_level<=30 then .65 else .5 end;v_xp:=case when v_need is null then 0 else ceil(v_need*(v_d.xp_basis_points/10000.0)*v_mult) end;perform public.core_mutate_xp(v_s.owner_player_id,p_run,v_s.owner_player_id,v_xp,'action',p_submission::text,gen_random_uuid(),encode(digest('action-xp:'||p_submission::text,'sha256'),'hex'));perform public.core_change_coins(v_s.owner_player_id,p_run,v_s.owner_player_id,v_d.coin_reward,'action',p_submission::text,gen_random_uuid(),encode(digest('action-coins:'||p_submission::text,'sha256'),'hex'));
insert into public.action_usages(game_run_id,player_id,action_id,submission_id,accepted_at,festival_day_key)values(p_run,v_s.owner_player_id,v_s.action_id,p_submission,v_now,v_day);if v_d.cooldown_seconds is not null then insert into public.action_cooldowns values(p_run,v_s.owner_player_id,v_s.action_id,v_now+make_interval(secs=>v_d.cooldown_seconds),p_submission,v_now)on conflict(game_run_id,player_id,action_id)do update set cooldown_ends_at=excluded.cooldown_ends_at,source_submission_id=excluded.source_submission_id,updated_at=v_now;end if;
insert into public.daily_quest_progress(game_run_id,player_id,festival_day_key,accepted_actions)values(p_run,v_s.owner_player_id,v_day,1)on conflict(game_run_id,player_id,festival_day_key)do update set accepted_actions=daily_quest_progress.accepted_actions+1,updated_at=v_now;insert into public.daily_quest_distinct_actions values(p_run,v_s.owner_player_id,v_day,v_s.action_id,v_now)on conflict do nothing;insert into public.daily_quest_progress(game_run_id,player_id,festival_day_key,successful_validations)values(p_run,p_actor,v_day,1)on conflict(game_run_id,player_id,festival_day_key)do update set successful_validations=daily_quest_progress.successful_validations+1,updated_at=v_now;
-- Quest eligibility is recorded uniquely; reward expansion is deterministic in the documented order.
perform public.core_record_event(p_run,v_s.owner_player_id,'daily_quest_progress_changed',jsonb_build_object('day',v_day));perform public.core_record_event(p_run,p_actor,'daily_quest_progress_changed',jsonb_build_object('day',v_day));perform public.action_complete_eligible_quests(p_run,v_s.owner_player_id,v_day,v_now);perform public.action_complete_eligible_quests(p_run,p_actor,v_day,v_now);
update public.player_run_states prs set current_hp=greatest(0,prs.current_hp-v_d.hp_cost),state_version=prs.state_version+1,updated_at=v_now where prs.game_run_id=p_run and prs.player_id=v_s.owner_player_id returning prs.* into v_owner;if v_owner.current_hp=0 and v_d.hp_cost>0 then v_penalty:=ceil(v_owner.total_xp*(case when v_owner.current_level<=10 then .05 when v_owner.current_level<=20 then .06 when v_owner.current_level<=30 then .07 else .08 end));perform public.core_mutate_xp(v_s.owner_player_id,p_run,v_s.owner_player_id,-v_penalty,'action_death',p_submission::text,gen_random_uuid(),encode(digest('action-death:'||p_submission::text,'sha256'),'hex'));update public.player_run_states prs set gameplay_status='hospitalized',deaths=prs.deaths+1,current_hp=0,state_version=prs.state_version+1 where prs.game_run_id=p_run and prs.player_id=v_s.owner_player_id;insert into public.hospital_stays(game_run_id,player_id,source_submission_id,started_at,hospital_until,xp_lost)values(p_run,v_s.owner_player_id,p_submission,v_now,v_now+interval '60 minutes',v_penalty);v_cancelled:=public.cancel_pending_actions_for_player(p_run,v_s.owner_player_id,'owner_hospitalized');perform public.core_record_event(p_run,v_s.owner_player_id,'player_hospitalized_from_action',jsonb_build_object('submissionId',p_submission));end if;perform public.core_record_event(p_run,v_s.owner_player_id,'action_accepted',jsonb_build_object('submissionId',p_submission,'validatorId',p_actor));v_result:=jsonb_build_object('submissionId',p_submission,'status','accepted','acceptedAt',v_now,'actionXp',v_xp,'actionCoins',v_d.coin_reward,'hpCost',v_d.hp_cost,'hospitalized',v_owner.current_hp=0 and v_d.hp_cost>0,'xpPenalty',v_penalty,'cancelledPending',v_cancelled);return v_result;end $$;

do $$declare n text;begin foreach n in array array['action_definitions','action_submissions','action_usages','action_cooldowns','daily_quest_progress','daily_quest_distinct_actions','daily_quest_completions','hospital_stays']loop execute format('alter table public.%I enable row level security',n);execute format('alter table public.%I force row level security',n);execute format('revoke all on table public.%I from public,anon,authenticated',n);end loop;end$$;
revoke all on function public.submit_action(uuid,uuid,text,uuid,text),public.accept_action_submission(uuid,uuid,uuid,uuid,text),public.reject_action_submission(uuid,uuid,uuid,uuid,text),public.cancel_pending_actions_for_player(uuid,uuid,public.action_cancellation_reason) from public,anon,authenticated;
grant execute on function public.submit_action(uuid,uuid,text,uuid,text),public.accept_action_submission(uuid,uuid,uuid,uuid,text),public.reject_action_submission(uuid,uuid,uuid,uuid,text),public.cancel_pending_actions_for_player(uuid,uuid,public.action_cancellation_reason) to service_role;
commit;
