begin;

-- Supabase installs pgcrypto in the extensions schema. These SECURITY DEFINER
-- functions deliberately keep their minimal public,pg_temp search_path and
-- resolve digest explicitly instead of trusting caller-controlled lookup.
create or replace function public.action_complete_eligible_quests(p_run uuid,p_player uuid,p_day date,p_at timestamptz)returns text[]
language plpgsql security definer set search_path=public,pg_temp as $$
declare v_progress public.daily_quest_progress%rowtype;v_distinct integer;v_quest text;v_xp_bp integer;v_coins integer;v_need integer;v_level integer;v_mult numeric;v_xp integer;v_done text[]:='{}';
begin select q.* into v_progress from public.daily_quest_progress q where q.game_run_id=p_run and q.player_id=p_player and q.festival_day_key=p_day for update;select count(*) into v_distinct from public.daily_quest_distinct_actions d where d.game_run_id=p_run and d.player_id=p_player and d.festival_day_key=p_day;
for v_quest,v_xp_bp,v_coins in values('easy_accepted_5',8000,15),('easy_validations_10',8000,15),('easy_variety_5',8000,15),('medium_accepted_10',14000,30),('medium_validations_15',14000,30),('hard_daily_mastery',23000,95) loop
 if (v_quest='easy_accepted_5' and v_progress.accepted_actions>=5)or(v_quest='easy_validations_10' and v_progress.successful_validations>=10)or(v_quest='easy_variety_5' and v_distinct>=5)or(v_quest='medium_accepted_10' and v_progress.accepted_actions>=10)or(v_quest='medium_validations_15' and v_progress.successful_validations>=15)or(v_quest='hard_daily_mastery' and v_progress.accepted_actions>=15 and v_progress.successful_validations>=20 and v_distinct>=7)then
  if not exists(select 1 from public.daily_quest_completions c where c.game_run_id=p_run and c.player_id=p_player and c.festival_day_key=p_day and c.quest_id=v_quest)then
   select prs.current_level into v_level from public.player_run_states prs where prs.game_run_id=p_run and prs.player_id=p_player for update;select t.requirement into v_need from public.level_xp_thresholds t where t.level=v_level;v_mult:=case when v_level<=10 then 1 when v_level<=20 then .8 when v_level<=30 then .65 else .5 end;v_xp:=case when v_need is null then 0 else ceil(v_need*(v_xp_bp/10000.0)*v_mult)end;
   perform public.core_mutate_xp(p_player,p_run,p_player,v_xp,'daily_quest',p_day::text||':'||v_quest,gen_random_uuid(),encode(extensions.digest(convert_to('quest-xp:'||p_run::text||':'||p_player::text||':'||p_day::text||':'||v_quest,'UTF8'),'sha256'::text),'hex'));perform public.core_change_coins(p_player,p_run,p_player,v_coins,'daily_quest',p_day::text||':'||v_quest,gen_random_uuid(),encode(extensions.digest(convert_to('quest-coins:'||p_run::text||':'||p_player::text||':'||p_day::text||':'||v_quest,'UTF8'),'sha256'::text),'hex'));
   insert into public.daily_quest_completions(game_run_id,player_id,festival_day_key,quest_id,xp_granted,coins_granted,completed_at)values(p_run,p_player,p_day,v_quest,v_xp,v_coins,p_at);perform public.core_record_event(p_run,p_player,'daily_quest_completed',jsonb_build_object('questId',v_quest,'xp',v_xp,'coins',v_coins));v_done:=array_append(v_done,v_quest);
  end if;
 end if;
end loop;return v_done;end $$;

create or replace function public.accept_action_submission(p_actor uuid,p_run uuid,p_submission uuid,p_idempotency_key uuid,p_request_hash text)returns jsonb
language plpgsql security definer set search_path=public,pg_temp as $$
declare v_s public.action_submissions%rowtype;v_d public.action_definitions%rowtype;v_owner public.player_run_states%rowtype;v_validator public.player_run_states%rowtype;v_existing public.idempotency_records%rowtype;v_now timestamptz:=clock_timestamp();v_day date;v_need integer;v_mult numeric;v_xp integer;v_penalty integer:=0;v_cancelled integer:=0;v_result jsonb;
begin perform public.action_assert_live(p_run);select s.* into v_s from public.action_submissions s where s.id=p_submission and s.game_run_id=p_run for update;if not found then raise exception 'NOT_FOUND';end if;if v_s.status<>'pending' then return jsonb_build_object('submissionId',v_s.id,'status',v_s.status);end if;if v_s.expires_at<=v_now then update public.action_submissions s set status='expired',resolved_at=v_now where s.id=p_submission;return jsonb_build_object('submissionId',p_submission,'status','expired');end if;if v_s.owner_player_id=p_actor then raise exception 'FORBIDDEN';end if;
select prs.* into v_owner from public.player_run_states prs where prs.game_run_id=p_run and prs.player_id=v_s.owner_player_id for update;select prs.* into v_validator from public.player_run_states prs where prs.game_run_id=p_run and prs.player_id=p_actor for update;if v_owner.gameplay_status<>'active' or v_validator.gameplay_status<>'active' then raise exception 'STATUS_BLOCKED';end if;if exists(select 1 from public.action_submissions x where x.game_run_id=p_run and x.owner_player_id=v_s.owner_player_id and x.status='accepted' and x.validator_player_id=p_actor and not exists(select 1 from public.action_submissions y where y.game_run_id=p_run and y.owner_player_id=v_s.owner_player_id and y.status='accepted' and y.accepted_at>x.accepted_at) order by x.accepted_at desc limit 1)then raise exception 'CONSECUTIVE_VALIDATOR';end if;select ad.* into v_d from public.action_definitions ad where ad.id=v_s.action_id;if not v_d.is_enabled then raise exception 'ACTION_UNAVAILABLE';end if;v_day:=public.action_day_key(v_now);if exists(select 1 from public.action_cooldowns c where c.game_run_id=p_run and c.player_id=v_s.owner_player_id and c.action_id=v_s.action_id and c.cooldown_ends_at>v_now)then raise exception 'COOLDOWN';end if;if v_d.daily_cap is not null and(select count(*) from public.action_usages u where u.game_run_id=p_run and u.player_id=v_s.owner_player_id and u.action_id=v_s.action_id and u.festival_day_key=v_day)>=v_d.daily_cap then raise exception 'DAILY_CAP';end if;if v_d.festival_cap is not null and(select count(*) from public.action_usages u where u.game_run_id=p_run and u.player_id=v_s.owner_player_id and u.action_id=v_s.action_id)>=v_d.festival_cap then raise exception 'FESTIVAL_CAP';end if;
update public.action_submissions s set status='accepted',validator_player_id=p_actor,accepted_at=v_now,resolved_at=v_now where s.id=p_submission;select requirement into v_need from public.level_xp_thresholds where level=v_owner.current_level;v_mult:=case when v_owner.current_level<=10 then 1 when v_owner.current_level<=20 then .8 when v_owner.current_level<=30 then .65 else .5 end;v_xp:=case when v_need is null then 0 else ceil(v_need*(v_d.xp_basis_points/10000.0)*v_mult) end;perform public.core_mutate_xp(v_s.owner_player_id,p_run,v_s.owner_player_id,v_xp,'action',p_submission::text,gen_random_uuid(),encode(extensions.digest(convert_to('action-xp:'||p_submission::text,'UTF8'),'sha256'::text),'hex'));perform public.core_change_coins(v_s.owner_player_id,p_run,v_s.owner_player_id,v_d.coin_reward,'action',p_submission::text,gen_random_uuid(),encode(extensions.digest(convert_to('action-coins:'||p_submission::text,'UTF8'),'sha256'::text),'hex'));
insert into public.action_usages(game_run_id,player_id,action_id,submission_id,accepted_at,festival_day_key)values(p_run,v_s.owner_player_id,v_s.action_id,p_submission,v_now,v_day);if v_d.cooldown_seconds is not null then insert into public.action_cooldowns values(p_run,v_s.owner_player_id,v_s.action_id,v_now+make_interval(secs=>v_d.cooldown_seconds),p_submission,v_now)on conflict(game_run_id,player_id,action_id)do update set cooldown_ends_at=excluded.cooldown_ends_at,source_submission_id=excluded.source_submission_id,updated_at=v_now;end if;
insert into public.daily_quest_progress(game_run_id,player_id,festival_day_key,accepted_actions)values(p_run,v_s.owner_player_id,v_day,1)on conflict(game_run_id,player_id,festival_day_key)do update set accepted_actions=daily_quest_progress.accepted_actions+1,updated_at=v_now;insert into public.daily_quest_distinct_actions values(p_run,v_s.owner_player_id,v_day,v_s.action_id,v_now)on conflict do nothing;insert into public.daily_quest_progress(game_run_id,player_id,festival_day_key,successful_validations)values(p_run,p_actor,v_day,1)on conflict(game_run_id,player_id,festival_day_key)do update set successful_validations=daily_quest_progress.successful_validations+1,updated_at=v_now;
perform public.core_record_event(p_run,v_s.owner_player_id,'daily_quest_progress_changed',jsonb_build_object('day',v_day));perform public.core_record_event(p_run,p_actor,'daily_quest_progress_changed',jsonb_build_object('day',v_day));perform public.action_complete_eligible_quests(p_run,v_s.owner_player_id,v_day,v_now);perform public.action_complete_eligible_quests(p_run,p_actor,v_day,v_now);
update public.player_run_states prs set current_hp=greatest(0,prs.current_hp-v_d.hp_cost),state_version=prs.state_version+1,updated_at=v_now where prs.game_run_id=p_run and prs.player_id=v_s.owner_player_id returning prs.* into v_owner;if v_owner.current_hp=0 and v_d.hp_cost>0 then v_penalty:=ceil(v_owner.total_xp*(case when v_owner.current_level<=10 then .05 when v_owner.current_level<=20 then .06 when v_owner.current_level<=30 then .07 else .08 end));perform public.core_mutate_xp(v_s.owner_player_id,p_run,v_s.owner_player_id,-v_penalty,'action_death',p_submission::text,gen_random_uuid(),encode(extensions.digest(convert_to('action-death:'||p_submission::text,'UTF8'),'sha256'::text),'hex'));update public.player_run_states prs set gameplay_status='hospitalized',deaths=prs.deaths+1,current_hp=0,state_version=prs.state_version+1 where prs.game_run_id=p_run and prs.player_id=v_s.owner_player_id;insert into public.hospital_stays(game_run_id,player_id,source_submission_id,started_at,hospital_until,xp_lost)values(p_run,v_s.owner_player_id,p_submission,v_now,v_now+interval '60 minutes',v_penalty);v_cancelled:=public.cancel_pending_actions_for_player(p_run,v_s.owner_player_id,'owner_hospitalized');perform public.core_record_event(p_run,v_s.owner_player_id,'player_hospitalized_from_action',jsonb_build_object('submissionId',p_submission));end if;perform public.core_record_event(p_run,v_s.owner_player_id,'action_accepted',jsonb_build_object('submissionId',p_submission,'validatorId',p_actor));v_result:=jsonb_build_object('submissionId',p_submission,'status','accepted','acceptedAt',v_now,'actionXp',v_xp,'actionCoins',v_d.coin_reward,'hpCost',v_d.hp_cost,'hospitalized',v_owner.current_hp=0 and v_d.hp_cost>0,'xpPenalty',v_penalty,'cancelledPending',v_cancelled);return v_result;end $$;

revoke all on function public.action_complete_eligible_quests(uuid,uuid,date,timestamptz) from public,anon,authenticated;
revoke all on function public.accept_action_submission(uuid,uuid,uuid,uuid,text) from public,anon,authenticated;
grant execute on function public.action_complete_eligible_quests(uuid,uuid,date,timestamptz) to service_role;
grant execute on function public.accept_action_submission(uuid,uuid,uuid,uuid,text) to service_role;

commit;
